<a href="https://colab.research.google.com/github/Adeelzafar/DeepLearning-Book/blob/main/Deep_Learning_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import math

In [12]:
scalar = [[5]]
print(scalar)

[[5]]


In [13]:
vector = [1,2,3]
print(vector)

[1, 2, 3]


In [14]:
matrix = [[1,2],[3,4]]
print(matrix)

[[1, 2], [3, 4]]


In [15]:
tensor = [[[1,2]
          ,[3,4]]
         ,[[5,6]
          ,[7,8]]]
tensor #array with more than 2 axes

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [16]:
print(np.array(scalar).shape)
print(np.array(vector).shape)
print(np.array(matrix).shape)
print(np.array(tensor).shape)



(1, 1)
(3,)
(2, 2)
(2, 2, 2)


In [17]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[2,4,6],[1,2,3]])
C = np.matmul(A,B) # matmul refers to matrix multiplication
C

array([[ 4,  8, 12],
       [10, 20, 30],
       [16, 32, 48]])

In [18]:
#Addition of arrays
print(B+C) #error would arise as the shapes arent similar

ValueError: ignored

In [19]:
# A*(B*C) == (A*B)*C the associative property of matrices
np.matmul(A,np.matmul(B,C)) == np.matmul(C,np.matmul(A,B))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
#matrix multiplication is not commutative always
# however the dot product is commutative
np.matmul(A,B) == np.matmul(B,A)


<ipython-input-20-303c15665b9b>:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.matmul(A,B) == np.matmul(B,A)


False

In [21]:
#Transpose of a matrix
# transpose flips a matrix alongside its diagonal
print(f"A={A}\nTranspose of A={np.transpose(A)}")

A=[[1 2]
 [3 4]
 [5 6]]
Transpose of A=[[1 3 5]
 [2 4 6]]


In [22]:
A = np.array([[1,2],[3,4]])
Identity = np.matmul(np.invert(A),A) # you dont use the invert function to calculate the inverse
Identity 

array([[-11, -16],
       [-19, -28]])

In [23]:
Identity = np.matmul(np.linalg.inv(A),A) 
Identity # it still isnt the identity matrix , cause of the multiplication processes (float values are never really the same)


array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [24]:
# Linear Dependence and Span:
#linear combination
v1 = np.array([0, 0, 1])
v2 = np.array([1,0,0])
v3 = np.array([0, 1, 0])
X = ([v1,v2,v3])
y = ([1,2,3])
scalars = np.linalg.solve(X,y) #v1*1 + v2*2 + v3*3 is the linear combination 
scalars


array([2., 3., 1.])

In [25]:
# Norm:

#The size of vectors are found by using a function called norm.

 #   The default norm is L2 (eucledian norm), denoted by ||x||
 #   The maximum norm is used to find the absolute value of the vector with the largest magnitude
 #   The frobenius norm is used to measure the size of the matrix


In [26]:
A = np.array([1,2,3])
norm1 = np.linalg.norm(A) #defualt it takes L2 norm , we can also specify the norm 
norm2 = np.linalg.norm(A,ord=np.inf)
#norm3 = np.linalg.norm(A,ord='fro') #results in error
# as frobenius norm is calculated for matrices and not vectors
print(norm1)
print(norm2)
#print(norm3)


3.7416573867739413
3.0


In [27]:
B = np.array([[1,2,3],[4,5,6]])
norm3 = np.linalg.norm(B,ord="fro")
print(norm3)

9.539392014169456


In [28]:
#Special Kinds of matrices and Vectors

   # Diagonal matrix
   # Symmetric matrix - the transpose of matrix is same as the matrix then its symmetric
   # Unit matrix
   # Orthonormal matrix
   # Orthogonal matrix



In [29]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [31]:
I = np.identity(4)
I


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.diag(I)

array([1., 1., 1., 1.])

In [33]:
# Eigen Decomposition:

#    Matrix is decomposed into set of eigenvalues and eigenvectors.
#   Av = λv , where v is the eigenvector and λ is the eigenvalue.


In [34]:
A = np.random.rand(5,5)
eig_val = np.linalg.eigvals(A)
eig_val #eigenvalue

array([ 2.26882049+0.j        ,  0.28729933+0.05217042j,
        0.28729933-0.05217042j, -0.48737185+0.j        ,
       -0.41220256+0.j        ])

In [35]:
eig_val,eig_vec = np.linalg.eig(A)
eig_vec #eigen vector

array([[-0.39674193+0.j        , -0.02188992-0.04411804j,
        -0.02188992+0.04411804j, -0.17440589+0.j        ,
        -0.00951353+0.j        ],
       [-0.55470255+0.j        ,  0.63779945+0.j        ,
         0.63779945-0.j        , -0.27016926+0.j        ,
         0.19209723+0.j        ],
       [-0.4310433 +0.j        ,  0.51650196-0.13619387j,
         0.51650196+0.13619387j,  0.71141429+0.j        ,
        -0.67901635+0.j        ],
       [-0.46775879+0.j        , -0.37017913+0.10350746j,
        -0.37017913-0.10350746j,  0.40196772+0.j        ,
        -0.36361191+0.j        ],
       [-0.36097688+0.j        , -0.38652879+0.09117211j,
        -0.38652879-0.09117211j, -0.4784379 +0.j        ,
         0.60805536+0.j        ]])

In [36]:
#Single Value Decomposition:

 #   If a matrix is not square then we should use this method instead of eigen decomposition as it is not defined


In [37]:
A = np.arange(24).reshape(4,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
U,s,vh = np.linalg.svd(A,full_matrices=True) #full_matrices is optional
print("U=",U,"\n","s=",s,"\n","vh=",vh)

U= [[-0.09979291 -0.83068729 -0.40715931 -0.36636225]
 [-0.32237784 -0.44280078  0.26980878  0.79196163]
 [-0.54496277 -0.05491426  0.68186037 -0.48483651]
 [-0.76754771  0.33297225 -0.54450984  0.05923713]] 
 s= [6.56235089e+01 4.18987869e+00 3.37349797e-15 5.88754515e-16] 
 vh= [[-0.33965997 -0.36609381 -0.39252765 -0.41896148 -0.44539532 -0.47182916]
 [ 0.6390936   0.40151391  0.16393422 -0.07364547 -0.31122516 -0.54880485]
 [ 0.38004339 -0.51347474 -0.3869646   0.64859118  0.01739346 -0.14558869]
 [-0.09997007  0.25663017 -0.37194951 -0.0829683   0.7551148  -0.45685709]
 [-0.5663029   0.25060266  0.26550379  0.61008706 -0.18758162 -0.37230899]
 [-0.03262685  0.55896768 -0.67857742  0.13887814 -0.31476046  0.32811892]]


In [39]:
#Moore-Penrose Pseudoinverse:

  #  Used to find the inverse of non invertible matrices.
  # Inverse to used to solve a system of equations.
  #  therefore by using this we will be able to find a value which is almost the solution.


In [40]:
M = np.arange(6).reshape(2,3)
M

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
#moore penrose pseudo inverse
M1 = np.linalg.pinv(M)
M1

array([[-0.77777778,  0.27777778],
       [-0.11111111,  0.11111111],
       [ 0.55555556, -0.05555556]])

In [42]:
M1.dot(M) #which gives a result which is quite close to the pseudo inverse.

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

In [43]:
# Trace Operator:

#    Trace is the sum of all the elements in the diagonal of the square matrix.
#    trace of matrix is equal to its transpose


In [44]:
M2 = np.arange(9).reshape(3,3)
M2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
trace1 = M2.trace()
trace1

12

In [46]:
#Determinant:

 #   it is equal to the products of all the eigenvalues in the matrices.
 #   The determinant lets us know about the transformations of the matrix.


In [47]:
A = np.ones(4).reshape(2,2)
A

array([[1., 1.],
       [1., 1.]])

In [48]:
A_det = np.linalg.det(A)
A_det

0.0

In [49]:
#Principal Component Analysis:

    

In [50]:
M = np.arange(12).reshape(4,3) #defining the data 
M


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
M_mean = np.mean(M.T, axis=1)#calculate the mean of each column
M_mean

array([4.5, 5.5, 6.5])

In [52]:
M_center = M - M_mean #centering the columns by subtracting column means
M_center

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

In [53]:
M_cov = np.cov(M_center.T)# covariance matrix of the centered matrix
M_cov

array([[15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.]])

In [54]:
eig_val,eig_vec = np.linalg.eig(M_cov) # finding the eigenvalues and eigenvectors
print(f"Eigenvalues={eig_val}\nEigenvectors={eig_vec}")

Eigenvalues=[ 0. 45.  0.]
Eigenvectors=[[-0.81649658  0.57735027  0.        ]
 [ 0.40824829  0.57735027 -0.70710678]
 [ 0.40824829  0.57735027  0.70710678]]


In [55]:
#projecting the reduced data
M_red = eig_vec.T.dot(M_center.T)
M_red.T # transposing the matrix for easier understanding

array([[ 4.99600361e-16, -7.79422863e+00, -2.77555756e-16],
       [ 1.66533454e-16, -2.59807621e+00, -1.66533454e-16],
       [-1.66533454e-16,  2.59807621e+00,  1.66533454e-16],
       [-4.99600361e-16,  7.79422863e+00,  2.77555756e-16]])

In [56]:
from sklearn.decomposition import PCA
pca = PCA(3) # creating an instance
pca.fit(M)
M_red1 = pca.transform(M)
M_red1

array([[-7.79422863e+00, -1.66533454e-15, -2.16493490e-15],
       [-2.59807621e+00, -5.55111512e-16, -4.99600361e-16],
       [ 2.59807621e+00,  5.55111512e-16,  4.99600361e-16],
       [ 7.79422863e+00,  1.66533454e-15,  2.16493490e-15]])